# Generated by Django 4.0.5 on 2022-06-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Done')], default=0, max_length=10),
        ),
    ]
