# Generated by Django 4.0.5 on 2022-06-04 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-datepublish',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='post',
            name='datepublish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datepublish'),
        ),
        migrations.AddField(
            model_name='post',
            name='dateupdated',
            field=models.DateTimeField(auto_now=True, verbose_name='dateupdated'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Published')], default=0, max_length=10),
        ),
    ]
